config/routes.rb
Flixter::Application.routes.draw do
  devise_for :users
  resource :dashboard, :only => [:show]
  root 'static_pages#index'
  get 'privacy', :to => 'static_pages#privacy'
  get 'team', :to => 'static_pages#team'
  get 'careers', :to => 'static_pages#careers'
  resources :courses, :only => [:index, :show] do
    resources :enrollments, :only => :create
  end
  resources :lessons, :only => [:show]
  namespace :instructor do
    resources :sections, :only => [:update]
    resources :lessons, :only => [:update]
    resources :sections, :only => [] do
      resources :lessons, :only => [:create]
    end
    resources :courses, :only => [:new, :create, :show] do
      resources :sections, :only => [:create]
    end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :sections
  has_many :images
  has_many :enrollments

  validates :title, :presence => true
  validates :description, :presence => true
  validates :cost, :presence => true, :numericality => {:greater_than_or_equal_to => 0}


  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :course
  belongs_to :user

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, :with_same => :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    
    return lesson
  end

end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
  has_many :lessons

  include RankedModel
  ranks :row_order, :with_same => :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first

    return section
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, :through => :enrollments, :source => :course
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   def enrolled_in?(course)
     return enrolled_courses.include?(course)
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
  end

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_course.premium?
      # Amount in cents
      @amount = (current_course.cost * 100).to_i

      customer = Stripe::Customer.create(
        :email => current_user.email,
        :card  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Flixter Premo Content',
        :currency    => 'usd'
      )
    end

    current_user.enrollments.create(:course => current_course)
    redirect_to course_path(current_course)
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end

end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def show
    @section = Section.new
    @lesson = Lesson.new
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render :text => "Unauthorized", :status => :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
    before_action :authenticate_user!
    before_action :require_authorized_for_current_section, :only => [:create]
    before_action :require_authorized_for_current_lesson, :only => [:update]

    def create
      @lesson = current_section.lessons.create(lesson_params)
      redirect_to instructor_course_path(current_section.course)
    end

    def update
      cl = Lesson.find(params[:id])
      # current_lesson.
      binding.pry
      cl.update_attributes(lesson_params)
      render :text => 'updated!'
    end

    private

    def require_authorized_for_current_lesson
      if current_lesson.section.course.user != current_user
        render :text => 'Unauthorized', :status => :unauthorized
      end
    end

    def current_lesson
      @current_lesson ||= Lesson.find(params[:id])
    end

    def require_authorized_for_current_section
      if current_section.course.user != current_user
        render :text => 'Unauthorized', :status => :unauthorized
      end
    end

    helper_method :current_section
    def current_section
      @current_section ||= Section.find(params[:section_id])
    end

    def lesson_params
      params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
    end
  end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, :only => [:create]
  before_action :require_authorized_for_current_section, :only => [:update]


  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

  def update
    current_section.update_attributes(section_params)
    render :text => 'updated!'
  end

  private

  def current_section
    @current_section ||= Section.find(params[:id])
  end

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      render :text => 'Unauthorized', :status => :unauthorized
    end
  end

  def require_authorized_for_current_course
    if current_course.user != current_user
      render :text => "Unauthorized", :status => :unauthorized
    end
  end

  helper_method :current_course
  def current_course
      if params[:course_id].present?
          @current_course ||= Course.find(params[:course_id])
      else
  	    @current_course ||= current_section.course
      end
  end

  def section_params
    params.require(:section).permit(:title, :row_order_position)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :enrolled_user

  def show
  end

  private

  helper_method :current_lesson

  def enrolled_user
    if !current_user.enrolled_in?(current_lesson.section.course)
      redirect_to course_path(current_lesson.section.course), :alert => 'You must be enrolled to view lessons in detail.'
    end
  end

  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def privacy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/index.html.erb
<br />

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center">Learn something today</h1>
  <br />

  <% @courses.each do |course| %>
    <h2 class="text-center"><%= link_to course.title, course_path(course) %></h2>
    <%= image_tag course.image, :class => 'img-responsive' %>
    <br />

    <div class="col-sm-8 col-sm-offset-1 col-xs-12">
      <%= course.description %>
    </div>
    <div class="col-sm-2 col-xs-12 text-center">
      <%= link_to 'More Details...', course_path(course), :class => 'btn btn-primary btn-large pull-right' %>
    </div>

    <br class="clr" />
    <br />
    <br />
  <% end %>
</div>

app/views/courses/show.html.erb
<br />

<div class="booyah-box col-xs-10 col-xs-offset-1">

  <h1><%= @course.title %></h1>
  <%= image_tag @course.image, :class => 'img-responsive' %>
  <br />

  <div class="col-sm-3 col-sm-offset-1 col-xs-12">
    <span class="label label-default">
      <%= number_to_currency @course.cost %>
    </span>


    <% if current_user && current_user.enrolled_in?(@course) %>
      <h3 class="label label-info">You Are Enrolled!</h3>
      <br />
    <% else %>
      <% if @course.free? %>
        <%= link_to 'Enroll', course_enrollments_path(@course), :class => 'btn btn-primary', :method => :post %>
        <br />
      <% else %>
        <%= form_tag course_enrollments_path(@course) do %>
          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="<%= @course.title %> (<%= number_to_currency @course.cost %>)"
                  data-amount="<%= (@course.cost * 100).to_i %>"></script>
        <% end %>
      <% end %>
    <% end %>
    <br />
    <% if current_user && current_user == @course.user %>
      <%= link_to 'Administer', instructor_course_path(@course), :class => 'btn btn-danger btn-large pull-left' %>
    <% end %>
  </div>

  <div class="col-sm-7 col-xs-12">
    <%= @course.description %>
  </div>

  <div class="col-xs-12">
    <% @course.sections.rank(:row_order).each do |section| %>
    <br /><br />
      <div class="section">
        <h3>
          <%= section.title %>
        </h3>
        <% section.lessons.rank(:row_order).each do |lesson| %>
          <div class="col-xs-12 col-sm-6">
            <div class="lesson text-center">
              <br />
              <%= link_to lesson_path(lesson) do %>
                <b><%= lesson.title %></b>
                <br />
                <%= lesson.subtitle %>
              <% end %>
            </div>
          </div>
        <% end %>
        <br class="clr" />
      </div>
    <% end %>
  </div>
</div>

app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a new course</h1>
  <%= simple_form_for @course, :url => instructor_courses_path, :html => {:multipart => true} do |f| %>
  <%= f.input :title %>
  <br />
  <%= f.input :description %>
  <br />
  <%= f.input :cost %>
  <br />
  <%= f.input :image %>
  <br />
  <%= f.submit "Create", :class => 'btn btn-primary' %>
  <br />
  <% end %>
<br />

</div>

app/views/instructor/courses/show.html.erb
<script>
  $(function() {
    $('.new-lesson-button').click(function( event ) {
      var lessonUrl = $( event.target).data('lesson-url');
      $('#newLessonForm').attr('action', lessonUrl);
    });

    $('.lessons').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() } }
        });
      }
    });


    $('.sections').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { section: { row_order_position: ui.item.index() } }
        });
      }
    });

  });
</script>

<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">

  <h1 class="text-center"><%= current_course.title %></h1>
  <%= image_tag current_course.image, :class => 'img-responsive' %>

  <br />

  <div class="col-sm-3 col-sm-offset-1 col-xs-12">
    <%= link_to 'Preview As Student...', course_path(current_course), :class => 'btn btn-warning pull-left' %>
  </div>

  <div class="col-sm-7 col-xs-12">
    <%= current_course.description %>
  </div>

  <br class="clr" />
  <br />

  <div class="text-center">

    <!-- Button trigger section modal -->
    <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newSectionModal">
      Add a new section...
    </button>
  </div>

  <ul class="sections">
    <% current_course.sections.rank(:row_order).each do |section| %>
      <li data-update-url="<%= instructor_section_path section %>" class="section-li">
        <div class="header pull-left">
          <span class="glyphicon glyphicon-list"></span>
          <%= section.title %>
        </div>

        <!-- Button trigger lesson modal -->
        <button class="btn btn-primary btn-sm pull-right new-lesson-button" data-toggle="modal" data-target="#newLessonModal" data-lesson-url="<%=instructor_section_lessons_path(section) %>">
          Add new lesson...
        </button>

        <br class="clr" />
        <br class="clr" />

        <ul class="lessons">
          <% section.lessons.rank(:row_order).each do |lesson| %>
            <li data-update-url="<%= instructor_lesson_path lesson %>">
              <div class="col-xs-1">
                <br />
                <span class="glyphicon glyphicon-list"></span>
              </div>
              <div class="col-xs-11 text-center">
                <p>
                  <b><%= lesson.title %></b>
                </p>
                <p>
                  <%= lesson.subtitle %>
                </p>
              </div>
              <br class="clr" />
            </li>
          <% end %>
        </ul>
        <br class="clr" />
      </li>
    <% end %>
  </ul>

</div>



<!-- Section Modal -->
<div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="newSectionModalLabel">Add a new section</h4>
      </div>
      <%= simple_form_for @section, :url => instructor_course_sections_path(current_course) do |f| %>
        <div class="modal-body">
            <%= f.input :title %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Add a section", :class => 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<!-- Lesson Modal -->
<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="newLessonModalLabel">Add a new lesson</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @lesson, :url => "#", :html => {:id => 'newLessonForm' } do |f| %>
          <%= f.input :title %>
          <%= f.input :subtitle %>
          <%= f.input :video %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Add the lesson", :class => 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/instructor/lessons/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a new lesson</h1>
  <%= simple_form_for @lesson, :url => instructor_section_lessons_path(current_section) do |f| %>
    <%= f.input :title %>
    <%= f.input :subtitle %>
    <%= f.file_field :video %>
    <br />
    <%= f.submit "Add the lesson" %>
    <br />
    <br />
  <% end %>
</div>

app/views/lessons/show.html.erb
<br />

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1><%= current_lesson.title %></h1>
  <p class="pull-left">
    <%= current_lesson.subtitle %>
  </p>

  <% if current_lesson.next_lesson.present? %>
    <%= link_to lesson_path(current_lesson.next_lesson), :class => 'btn btn-default pull-right' do %>
      Next Lesson &nbsp;
      <span class="glyphicon glyphicon-forward"></span>
    <% end %>
  <% end %>

  <br class="clr" />
  <br />

  <video id="MY_VIDEO_1" class="video-js vjs-default-skin vjs-big-play-centered" controls
 preload="auto" width="auto" height="auto" poster="/assets/black.jpg"
 data-setup="{}">
   <source src="<%= current_lesson.video.to_s %>" type='video/mp4'>
   <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
 </video>


</div>