config/routes.rb
Flixter::Application.routes.draw do
  devise_for :users
  resource :dashboard, :only => [:show]
  root 'static_pages#index'
  get 'privacy', :to => 'static_pages#privacy'
  get 'team', :to => 'static_pages#team'
  get 'careers', :to => 'static_pages#careers'
  resources :courses, :only => [:index, :show] do
    resources :enrollments, :only => :create
  end
  resources :lessons, :only => [:show]
  namespace :instructor do
    resources :sections, :only => [:update]
    resources :lessons, :only => [:update]
    resources :sections, :only => [] do
      resources :lessons, :only => [:create]
    end
    resources :courses, :only => [:new, :create, :show] do
      resources :sections, :only => [:create]
    end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :sections
  has_many :images
  has_many :enrollments

  validates :title, :presence => true
  validates :description, :presence => true
  validates :cost, :presence => true, :numericality => {:greater_than_or_equal_to => 0}


  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end

end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :course
  belongs_to :user

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, :with_same => :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    
    return lesson
  end

end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
  has_many :lessons

  include RankedModel
  ranks :row_order, :with_same => :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first

    return section
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, :through => :enrollments, :source => :course
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   def enrolled_in?(course)
     return enrolled_courses.include?(course)
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
  end

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_course.premium?
      # Amount in cents
      @amount = (current_course.cost * 100).to_i

      customer = Stripe::Customer.create(
        :email => current_user.email,
        :card  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Flixter Premo Content',
        :currency    => 'usd'
      )
    end

    current_user.enrollments.create(:course => current_course)
    redirect_to course_path(current_course)
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :enrolled_user

  def show
  end

  private

  helper_method :current_lesson

  def enrolled_user
    if !current_user.enrolled_in?(current_lesson.section.course)
      redirect_to course_path(current_lesson.section.course), :alert => 'You must be enrolled to view lessons in detail.'
    end
  end

  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def privacy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flixter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="http://vjs.zencdn.net/4.6/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/4.6/video.js"></script>
  <style>
    .video-js {padding-top: 56.25%}
    .vjs-fullscreen {padding-top: 0px}
  </style>
</head>
<body>

    <div id="wrap">
      <nav class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Flixter', root_path, :class => 'navbar-brand' %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'Browse Courses', courses_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><%= link_to 'My Dashboard', dashboard_path %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></li>
              <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>

  <br class="clr" />

  <div id="footer">
    <div class="container">
      <div class="col-xs-12 col-sm-3">
        <b>Teachers</b>
        <br/>
        <%= link_to 'Teach a Course', new_instructor_course_path %>
        <br />
        <%= link_to 'My Dashboard', dashboard_path %>
      </div>
      <div class="col-xs-12 col-sm-3">
        <b>About</b>
        <br />
        <%= link_to 'Team', team_path %>
        <br />
        <%= link_to 'Careers', careers_path %>
        <br />
        <%= link_to 'Privacy Policy', privacy_path %>
      </div>
      <div class="col-xs-12 col-sm-3">
         <b>Contact</b>
         <br />
         tifkim.com
         <br />
         Madison, WI
         <br />
       </div>
       <div class="col-xs-12 col-sm-3 social">
         <b>Social</b>
         <br />
         <%= link_to 'http://github.com/tifkim' do %>
           <%= image_tag 'github.png', :class => 'social-button' %>
         <% end %>
         <%= link_to 'http://twitter.com/kimprint' do %>
           <%= image_tag 'twitter.png', :class => 'social-button' %>
         <% end %>
       </div>
    </div>
  </div>

</body>
</html>